## Matrix Decomposition - LU and QR

### LU Decomposition

In numerical analysis and linear algebra, LU decomposition is used to factor a matrix into two matrices $\textbf{L}$ and $\textbf{U}$ which are lower triangular and upper triangluar matrices respectively. 

It helps in the following :-

- Solving a system of linear equations through Gaussian elimination
- Finding inverse of a matrix
- Computing the determinant of a matrix

$$\textbf{A} = \textbf{L}\textbf{U}$$

$$\begin{bmatrix} a_{11} & a_{12} & a_{13} \\  a_{21} & a_{22} & a_{23} \\  a_{31} & a_{32} & a_{33} \end{bmatrix}  = \begin{bmatrix} l_{11} & 0 & 0 \\  l_{21} & l_{22} & 0 \\  l_{31} & a_{32} & a_{33} \end{bmatrix} \begin{bmatrix} u_{11} & u_{12} & u_{13} \\  u_{21} & u_{22} & 0 \\  u_{31} & 0 & 0 \end{bmatrix}$$

**What is the use of LU decomposition ?**

It summerises the Gaussian elimination in matrix form.

**What are the conditions for LU decomposition to exist ?**

- A should be a square matrix 
- Permuation matrix should be 0

Exapanding on the last point, it is not always possible to decompose the matrix into a lower triangular and upper triangular matrix, say if $a_{11}=0$ in original matrix then either $u_{11}$ or $l_{11}$ has to be 0. This means that either $\textbf{L}$ or $\textbf{U}$ should be non-invertible (All 0's in one row). However, this is not possible as  $\textbf{A}$ is invertible. This problem can be solved by just reordering the rows of $\textbf{A}$ so that the first element of permuted matrix is not 0.

**Decompose the following matrix into a lower and upper triangular matrix.**

$$ \textbf{A} = \begin{bmatrix} 1 & -2 & -2 & -3 \\ 3 & -9 & 0 & -9 \\ -1 & 2 & 4 & 7 \\ -3 & -6 & 26 & 2 \end{bmatrix}$$

In [8]:
import numpy as np
A = np.array([[1,-2,-2,-3],[3,-9,0,-9],[-1,2,4,7],[-3,-6,26,2]], dtype='float64')
print (A)

def LU(A):
    
    U = np.copy(A)
    m, n = A.shape
    L = np.eye(n)
    
    # to be filled

L,U = LU(A)

[[ 1. -2. -2. -3.]
 [ 3. -9.  0. -9.]
 [-1.  2.  4.  7.]
 [-3. -6. 26.  2.]]


### Application 

### QR Decomposition